version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: my-nginx
    ports:
      - "80:80"
#      - "443:443"  # Uncomment if ssl is enabled
    env_file:
      - .env
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/forkapi/static/:ro
      - web_media:/forkapi/media/
      - ./nginx/ssl:/forkapi/nginx/ssl
    command: /bin/sh -c "envsubst < /etc/nginx/sites-enabled/forkapi.nginx.template > /etc/nginx/sites-enabled/forkapi.nginx.conf && nginx -g 'daemon off;'"
    networks:
      - foodie_network
    depends_on:
      - web

  web:
    image: mikebgrep/forkapi:latest
    container_name: forkapi-from-image
    env_file:
      - .env
    restart: always
    command: >
      sh -c "uwsgi --ini uwsgi.ini --chown-socket=www-data:www-data"
    volumes:
      - data:/forkapi/sql/
      - uwsgi_data:/tmp/uwsgi/
      - web_media:/forkapi/media/
      - web_static:/forkapi/static/
    networks:
      - foodie_network

volumes:
  data:
  uwsgi_data:
  web_static:
  web_media:

networks:
  foodie_network:
    driver: bridge